name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform_test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Init
        run: terraform init -backend=false

      - name: Validate
        run: terraform validate

      - name: Test
        run: terraform test
